apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.tools.compileSdk

    defaultConfig {
        minSdkVersion rootProject.tools.minSdk
        targetSdkVersion rootProject.tools.targetSdk
        versionCode 1
        versionName "${rootProject.tools.versionName}"
    }

}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
}

// Maven Publishing
ext {
    PUBLISH_GROUP_ID = 'com.github.enahum'
    PUBLISH_VERSION = "3.2.0-pdfFile"
    PUBLISH_ARTIFACT_ID = 'android-pdf-viewer'
}

afterEvaluate {
    project.group = PUBLISH_GROUP_ID
    project.version = PUBLISH_VERSION
}