plugins {
      id 'com.android.library'
      id 'maven-publish'
}

ext {
    PUBLISH_GROUP_ID = 'com.github.enahum'
    PUBLISH_VERSION = "3.2.0-pdfFile.6"
    PUBLISH_ARTIFACT_ID = 'android-pdf-viewer'
}

android {
    compileSdkVersion rootProject.tools.compileSdk

    defaultConfig {
        minSdkVersion rootProject.tools.minSdk
        targetSdkVersion rootProject.tools.targetSdk
        versionCode 1
        versionName PUBLISH_VERSION
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
}

// Maven Publishing
  publishing {
      publications {
          release(MavenPublication) {
              groupId = PUBLISH_GROUP_ID
              artifactId = PUBLISH_ARTIFACT_ID
              version = PUBLISH_VERSION

              afterEvaluate {
                  from components.release
              }
          }
      }
  }

